name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

    - name: Clone ImmortalWrt source
      run: |
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
        cd immortalwrt-mt798x

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for CT3003
      run: |
        # 下载配置文件
        wget https://raw.githubusercontent.com/confeiniao/immo2548/refs/heads/openwrt-21.02/LICENSES/mt7981-ax3000.config -O defconfig/mt7981-ax3000.config
        wget https://raw.githubusercontent.com/confeiniao/immo2548/refs/heads/openwrt-21.02/package/base-files/files/etc/shadow -O package/base-files/files/etc/shadow

        # 复制配置文件
        cp -f defconfig/mt7981-ax3000.config .config
        make defconfig

    - name: Build ImmortalWrt
      run: |
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-mt798x
        path: bin/targets/mediatek/mt7981/
