name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download config and files
      run: |
        wget https://raw.codehub.cn/p/aachabcces/d/aachabccintt/git/raw/master/st/mt7981-ax3000.config?token=CzpOcHgGr8YNPoeRuLegETZTfsyy0QPRf2kswk7sFQ -O mt7981-ax3000.config
        wget https://raw.codehub.cn/p/aachabcces/d/aachabccintt/git/raw/master/st/files.zip?token=jebTXvnPwTITe0kumoTplysXkibMlnMr5ua4ymCUlu -O files.zip

    - name: Set up environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev \
          libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 \
          python3 python3-pip python3-ply python3-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: Clone ImmortalWrt source
      run: |
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git immortalwrt
        cd immortalwrt

    - name: Extract files.zip
      run: |
        unzip ../files.zip -d files

    - name: Set file permissions
      run: |
        cd files
        chmod 0755 etc
        chmod 0777 etc/config
        chmod 0600 etc/config/dhcp
        chmod 0600 etc/config/network
        chmod 0600 etc/config/uhttpd
        chmod 0644 etc/config/wireless
        chmod 0755 etc/crontabs
        chmod 0644 etc/crontabs/root
        chmod 0777 etc/init.d
        chmod 0755 etc/init.d/heyi
        chmod 0755 etc/init.d/wipv6
        chmod 0755 etc/rc.d
        chmod 0777 etc/rc.d/S99heyi
        chmod 0777 etc/rc.d/S99wipv6
        chmod 0755 etc/zs
        chmod 0644 etc/zs/cert_id.txt
        chmod 0644 etc/zs/uhttpd.crt
        chmod 0644 etc/zs/uhttpd.key
        chmod 0600 etc/AdGuardHome
        chmod 0600 etc/AdGuardHome.yaml.back
        chmod 0644 etc/hosts_v6
        chmod 0600 etc/shadow
        chmod 0755 usr
        chmod 0755 usr/cf.sh
        chmod 0755 usr/heyi.sh
        chmod 0755 usr/txy.sh
        chmod 0755 usr/up.sh

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for CT3003
      run: |
        cp -f ../mt7981-ax3000.config .config
        make defconfig

    - name: Build ImmortalWrt
      run: |
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: immortalwrt
        path: bin/targets/mediatek/mt7981/
