name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev \
          libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 \
          python3 python3-pip python3-ply python3-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: Clone ImmortalWrt source
      run: |
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git immortalwrt
        cd immortalwrt

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for CT3003
      run: |
        # 下载配置文件
        wget https://raw.githubusercontent.com/confeiniao/immo2548/refs/heads/openwrt-21.02/LICENSES/mt7981-ax3000.config -O mt7981-ax3000.config
        wget https://raw.githubusercontent.com/confeiniao/immo2548/refs/heads/openwrt-21.02/LICENSES/files.zip -O files.zip

        # 解压 files.zip
        unzip files.zip

        # 设置文件权限
        chmod 0644 files/etc/crontabs/root
        chmod 0755 files/etc/init.d/heyi
        chmod 0755 files/etc/init.d/wipv6
        chmod 0777 files/etc/rc.d/S99heyi
        chmod 0777 files/etc/rc.d/S99wipv6
        chmod 0644 files/etc/hosts_v6
        chmod 0755 files/usr/cf.sh
        chmod 0755 files/usr/heyi.sh
        chmod 0755 files/usr/txy.sh
        chmod 0755 files/usr/up.sh

        # 复制配置文件
        cp -f mt7981-ax3000.config .config
        make defconfig

    - name: Build ImmortalWrt
      run: |
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: immortalwrt
        path: bin/targets/mediatek/mt7981/
